[build]
  command = "npm run build"
  functions = "functions"
  NODE_ENV = "18"
  publish = "/build"

[dev]
  port = 18080
  publish = "/build"
  command = "npm run dev"

[production]
  publish = "/build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"